databases:
  - name: emp-db
    plan: free
    databaseName: empdb
    user: empuser

services:
  - type: web
    name: emp-project-backend
    plan: free
    runtime: docker
    rootDir: emp-project
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: emp-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: emp-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: emp-db
          property: database
      - key: DATABASE_USERNAME
        fromDatabase:
          name: emp-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: emp-db
          property: password
      - key: FRONTEND_URL
        value: https://emp-project-view.onrender.com

  - type: static
    name: emp-project-view
    rootDir: emp-project/emp-project-view
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://emp-project-backend.onrender.com
